##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://ams118.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /woolseytest
# location of code, the full url to your github repository
source-code: https://github.com/ams118/woolsey_test

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Woolsey Fire Memory Project
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Photographs, videos, oral history recordings, and written accounts documenting the 2018 Woolsey Fire by members of the Malibu community.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: The Woolsey Fire Memory Project collects, preserves, and presents the history of the Woolsey Fire and its impact on our local community, with a focus on Malibu and Pepperdine University. The goals of this project are to help community members process and heal from this disastrous event by sharing their stories, and to preserve a record of the event for future generations.  
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: annaspeth
# Organization branding
organization-name: Pepperdine University Libraries
organization-link: https://pepperdine.contentdm.oclc.org/digital/
organization-logo-banner: https://pepperdine.contentdm.oclc.org/customizations/global/images/pepperdine-libraries-digital-collections2.png
organization-logo-nav: https://pepperdine.contentdm.oclc.org/customizations/global/images/pepperdine-libraries-digital-collections2.png


##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: woolseycb
# contentdm collection name, matches collection ID used by CDM
cdm-collection-id: /p15730coll30
# CONTENTdm server url
cdm-url: https://cdm15730.contentdm.oclc.org
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'woolseycb'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code
# if present, used to add analytics during "production" build only
# google-analytics-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
